/**
 * Worker Code Generator for Cloudflare Workers deployment.
 *
 * Instead of extracting tool code via fragile regex (like the Pinchers platform does),
 * the open source CLI uses a clean import pattern:
 *   - User writes tools in src/tools.ts with registerTools(server, storage)
 *   - This module generates src/_worker.ts that imports registerTools
 *   - The worker uses McpAgent (Durable Objects) for production MCP hosting
 *
 * The generated worker is a build artifact (gitignored), not user code.
 */

export interface WorkerGenConfig {
  /** Tool display name */
  name: string;
  /** Tool version */
  version: string;
  /** Whether the tool uses the storage API */
  usesStorage: boolean;
  /** Whether the tool uses D1 database (env.DB) */
  usesD1: boolean;
}

/**
 * Generate the CF Worker entry point that imports from tools.ts.
 */
export function generateWorkerEntry(config: WorkerGenConfig): string {
  // Build Env type based on what bindings are needed
  const envBindings = [
    '  MCP_OBJECT: DurableObjectNamespace;',
  ];
  if (config.usesStorage) {
    envBindings.push('  TOOL_KV: KVNamespace;');
  }
  if (config.usesD1) {
    envBindings.push('  DB: D1Database;');
  }

  const envType = `type Env = {\n${envBindings.join('\n')}\n};`;

  const storageInit = config.usesStorage
    ? `    // KV-backed persistent storage (same API as local dev)
    const kv = this.env.TOOL_KV;
    const storage = {
      get: async (key: string) => { const v = await kv.get(key); return v ? JSON.parse(v) : null; },
      set: async (key: string, value: any) => { await kv.put(key, JSON.stringify(value)); },
      delete: async (key: string) => { await kv.delete(key); },
      keys: async (prefix?: string) => {
        const list = await kv.list(prefix ? { prefix } : undefined);
        return list.keys.map((k: any) => k.name);
      }
    };

`
    : `    // No-op storage (tool doesn't use persistence)
    const storage = {
      get: async (_key: string) => null,
      set: async (_key: string, _value: any) => {},
      delete: async (_key: string) => {},
      keys: async (_prefix?: string) => [] as string[],
    };

`;

  return `// Auto-generated by pinch CLI — do not edit manually.
// Source: src/tools.ts → deployed as Cloudflare Worker with Durable Objects.

import { McpAgent } from "agents/mcp";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { registerTools } from "./tools.js";

${envType}

// ── MCP Agent (Durable Object) ──────────────────────────
export class ToolMCP extends McpAgent<Env> {
  server = new McpServer({
    name: "${config.name}",
    version: "${config.version}",
  });

  async init() {
${storageInit}    registerTools(this.server, storage);
  }
}

// ── Worker entry point ──────────────────────────────────
export default {
  async fetch(
    request: Request,
    env: Env,
    ctx: ExecutionContext
  ): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === "/" || url.pathname === "/health") {
      return Response.json({
        name: "${config.name}",
        version: "${config.version}",
        status: "ok",
        mcp: "/mcp",
      });
    }

    if (url.pathname === "/mcp" || url.pathname === "/sse") {
      return ToolMCP.serve(url.pathname).fetch(request, env, ctx);
    }

    return new Response("Not found", { status: 404 });
  },
};
`;
}

/**
 * Generate a production-ready wrangler.toml.
 */
export function generateWranglerConfig(
  slug: string,
  name: string,
  opts: { usesStorage?: boolean; usesD1?: boolean; kvId?: string; d1DatabaseId?: string } = {}
): string {
  let config = `# ${name} — MCP Server on Cloudflare Workers
# Generated by pinch CLI (https://github.com/AndrewLeonardi/pinch-cli)
#
# Deploy: pinch deploy
# Or manually: npx wrangler deploy

name = "${slug}"
main = "src/_worker.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "ToolMCP"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ToolMCP"]
`;

  if (opts.usesStorage) {
    config += `
# Persistent key-value storage
# Created automatically by: pinch deploy
[[kv_namespaces]]
binding = "TOOL_KV"
id = "${opts.kvId || ""}"
`;
  }

  if (opts.usesD1) {
    config += `
# D1 SQL database
# Created automatically by: pinch deploy
[[d1_databases]]
binding = "DB"
database_name = "${slug}-db"
database_id = "${opts.d1DatabaseId || ""}"
`;
  }

  return config;
}

/**
 * Detect if tool source code uses the storage API.
 */
export function detectStorageUsage(sourceCode: string): boolean {
  return (
    sourceCode.includes("storage.get(") ||
    sourceCode.includes("storage.set(") ||
    sourceCode.includes("storage.delete(") ||
    sourceCode.includes("storage.keys(")
  );
}

/**
 * Detect if tool source code uses D1 database (env.DB).
 */
export function detectD1Usage(sourceCode: string): boolean {
  return sourceCode.includes("env.DB");
}
